name: "Jira Issue Key Checker"
on:
  pull_request:
    branches: [main]
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fgiuliani/jira-issue-key-checker@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          jira-prefix: 'PLAT'
