name: list PR commit messages
on:
 pull_request:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: List the SHA and commit message for every commit of the PR
       run: |
          curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits | jq -r  '.[] | [.sha,.commit.message]'
